DROP TABLE IF EXISTS `phpmq_message`;
CREATE TABLE IF NOT EXISTS `phpmq_message` (
`m_id` bigint(8) NOT NULL COMMENT 'Simple rolling counter (no real use except to keep mySQL happy)',
  `mq_id` bigint(8) NOT NULL DEFAULT '0' COMMENT 'The queue that this message is targeted',
  `m_msg` text NOT NULL COMMENT 'The message to the task processor in JSON format',
  `m_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When message was received',
  `m_log` text COMMENT 'Log of task (reserved for later)',
  `m_respond` varchar(128) DEFAULT NULL COMMENT 'url to poll on completion',
  `m_status` enum('new','open','done','closed','failed') NOT NULL DEFAULT 'new',
  `m_started` timestamp NULL DEFAULT NULL COMMENT 'When the task processor was last initiated',
  `m_reply` text COMMENT 'Task response in JSON format',
  `m_rc` int(11) NOT NULL DEFAULT '0' COMMENT 'Consume return code',
  `m_completed` timestamp NULL DEFAULT NULL COMMENT 'When the task completed processing and returned',
  `m_errors` int(11) NOT NULL DEFAULT '0' COMMENT 'The number of times this task entry has failed',
  `m_uuid` varchar(36) NOT NULL DEFAULT '' COMMENT 'Message uuid generated by the server for api access'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `phpmq_queue`;
CREATE TABLE IF NOT EXISTS `phpmq_queue` (
`mq_id` bigint(8) NOT NULL COMMENT 'Internal message queue id',
  `mq_name` varchar(64) NOT NULL COMMENT 'The name used to access this queue programtically',
  `mq_type` enum('message','api','fork','intval','dataval') NOT NULL DEFAULT 'message' COMMENT 'What type of queue is this',
  `mq_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Note of when this Queue wa sinitially written to (or created ''manually'')',
  `mq_timeout` int(8) NOT NULL DEFAULT '30' COMMENT 'Retry timeout',
  `mq_maxerrors` int(11) NOT NULL DEFAULT '5' COMMENT 'Maximum number of times to try a task before giving up',
  `mq_desc` text COMMENT 'Additional (optional) comments about this queue',
  `mq_respond` varchar(128) DEFAULT NULL COMMENT 'Optional url to send response information (overriden by m_respond)n/loop',
  `mq_intval` bigint(8) DEFAULT NULL COMMENT 'Value for queue type intval (otherwise null)',
  `mq_data` text COMMENT 'Value for queue type dataval and fork with list of messages queues to write to (otherwise null)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `phpmq_message` ADD PRIMARY KEY (`m_id`), ADD UNIQUE KEY `m_uuid` (`m_uuid`);
ALTER TABLE `phpmq_queue` ADD PRIMARY KEY (`mq_id`), ADD UNIQUE KEY `mq_name` (`mq_name`);
ALTER TABLE `phpmq_message` MODIFY `m_id` bigint(8) NOT NULL AUTO_INCREMENT COMMENT 'Simple rolling counter (no real use except to keep mySQL happy)',AUTO_INCREMENT=2;
ALTER TABLE `phpmq_queue` MODIFY `mq_id` bigint(8) NOT NULL AUTO_INCREMENT COMMENT 'Internal message queue id';